<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PlatformName>windows</PlatformName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>False</UseWindowsForms>
    <Configurations>Debug;Release</Configurations>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>PDFDeSecure.Program</StartupObject>
    <ErrorReport>none</ErrorReport>
    <FileAlignment>4096</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Label="Avalonia">
    <AvaloniaNameGeneratorBehavior>InitializeComponent</AvaloniaNameGeneratorBehavior>
    <NoWin32Manifest>true</NoWin32Manifest>
    <Authors>琴梨梨OvO</Authors>
    <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Gemini_Generated_Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>full</DebugType>
    <PublishTrimmed>False</PublishTrimmed>
    <PublishAot>False</PublishAot>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>none</DebugType>
    <PublishTrimmed>True</PublishTrimmed>
    <PublishAot>True</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Gemini_Generated_Icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.1" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.2.0" />
    <PackageReference Include="PDFsharp">
      <Version>6.2.0</Version>
    </PackageReference>
  </ItemGroup>
</Project>